version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.18.0
    commands:
      - echo "Instalando dependencias..."
      - npm install
  build:
    commands:
      - echo "Compilando proyecto..."
      - npm run build
  post_build:
    commands:
      - echo "Contenido del workspace:"
      - ls -lah
      - echo "Contenido de dist:"
      - ls -lah dist || true
      - echo "Desplegando en S3..."
      - aws s3 sync dist/ s3://wilsonvasquezcv/ --delete
  artifacts:
    files:
    - '**/*'
  base-directory: dist

